# Generated by Django 4.2.1 on 2023-05-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('profileURL', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('user_created_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('taskImgURL', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_creator', to=settings.AUTH_USER_MODEL)),
                ('tasked_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assignedto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
