# Generated by Django 4.2 on 2023-05-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('imgURL', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspace.user')),
                ('tasked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks1', to='workspace.user')),
            ],
        ),
    ]
