# Generated by Django 4.2 on 2023-05-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_creator', to='workspace.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasked_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assignedto', to='workspace.user'),
        ),
    ]
