# Generated by Django 4.2 on 2023-05-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_task_created_by_alter_task_tasked_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_created_date',
        ),
    ]
