# Generated by Django 4.2 on 2023-05-02 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_remove_user_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 2, 11, 36, 15, 773787, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
