# Generated by Django 4.2 on 2023-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_remove_task_imgurl_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='created_by_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasked_to',
            new_name='tasked_to_id',
        ),
    ]
